version: '3.8'

services:
  # This is your main application service, which runs Nginx and the Python backend together.
  app:
    build: .
    ports:
      - "80:80" # We map our local port 80 to the container's Nginx port 80.
    environment:
      # Pass the database connection details to your server.py
      - MONGO_URL=mongodb://mongo:27017/
      - DB_NAME=boardgame_db
      - JWT_SECRET_KEY=a-super-secret-key-you-should-change-later
    depends_on:
      - mongo

  # This is the MongoDB database service. It remains the same.
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
